/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sequential_algorithms.types;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GroupByComplex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -468985482510422244L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GroupByComplex\",\"namespace\":\"sequential_algorithms.types\",\"fields\":[{\"name\":\"key\",\"type\":\"int\"},{\"name\":\"sum\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GroupByComplex> ENCODER =
      new BinaryMessageEncoder<GroupByComplex>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GroupByComplex> DECODER =
      new BinaryMessageDecoder<GroupByComplex>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GroupByComplex> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GroupByComplex> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GroupByComplex> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GroupByComplex>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GroupByComplex to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GroupByComplex from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GroupByComplex instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GroupByComplex fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int key;
  @Deprecated public long sum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GroupByComplex() {}

  /**
   * All-args constructor.
   * @param key The new value for key
   * @param sum The new value for sum
   */
  public GroupByComplex(java.lang.Integer key, java.lang.Long sum) {
    this.key = key;
    this.sum = sum;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return sum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.Integer)value$; break;
    case 1: sum = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public int getKey() {
    return key;
  }


  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(int value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'sum' field.
   * @return The value of the 'sum' field.
   */
  public long getSum() {
    return sum;
  }


  /**
   * Sets the value of the 'sum' field.
   * @param value the value to set.
   */
  public void setSum(long value) {
    this.sum = value;
  }

  /**
   * Creates a new GroupByComplex RecordBuilder.
   * @return A new GroupByComplex RecordBuilder
   */
  public static sequential_algorithms.types.GroupByComplex.Builder newBuilder() {
    return new sequential_algorithms.types.GroupByComplex.Builder();
  }

  /**
   * Creates a new GroupByComplex RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GroupByComplex RecordBuilder
   */
  public static sequential_algorithms.types.GroupByComplex.Builder newBuilder(sequential_algorithms.types.GroupByComplex.Builder other) {
    if (other == null) {
      return new sequential_algorithms.types.GroupByComplex.Builder();
    } else {
      return new sequential_algorithms.types.GroupByComplex.Builder(other);
    }
  }

  /**
   * Creates a new GroupByComplex RecordBuilder by copying an existing GroupByComplex instance.
   * @param other The existing instance to copy.
   * @return A new GroupByComplex RecordBuilder
   */
  public static sequential_algorithms.types.GroupByComplex.Builder newBuilder(sequential_algorithms.types.GroupByComplex other) {
    if (other == null) {
      return new sequential_algorithms.types.GroupByComplex.Builder();
    } else {
      return new sequential_algorithms.types.GroupByComplex.Builder(other);
    }
  }

  /**
   * RecordBuilder for GroupByComplex instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GroupByComplex>
    implements org.apache.avro.data.RecordBuilder<GroupByComplex> {

    private int key;
    private long sum;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sequential_algorithms.types.GroupByComplex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sum)) {
        this.sum = data().deepCopy(fields()[1].schema(), other.sum);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GroupByComplex instance
     * @param other The existing instance to copy.
     */
    private Builder(sequential_algorithms.types.GroupByComplex other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sum)) {
        this.sum = data().deepCopy(fields()[1].schema(), other.sum);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public int getKey() {
      return key;
    }


    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public sequential_algorithms.types.GroupByComplex.Builder setKey(int value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public sequential_algorithms.types.GroupByComplex.Builder clearKey() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sum' field.
      * @return The value.
      */
    public long getSum() {
      return sum;
    }


    /**
      * Sets the value of the 'sum' field.
      * @param value The value of 'sum'.
      * @return This builder.
      */
    public sequential_algorithms.types.GroupByComplex.Builder setSum(long value) {
      validate(fields()[1], value);
      this.sum = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sum' field has been set.
      * @return True if the 'sum' field has been set, false otherwise.
      */
    public boolean hasSum() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sum' field.
      * @return This builder.
      */
    public sequential_algorithms.types.GroupByComplex.Builder clearSum() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GroupByComplex build() {
      try {
        GroupByComplex record = new GroupByComplex();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.Integer) defaultValue(fields()[0]);
        record.sum = fieldSetFlags()[1] ? this.sum : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GroupByComplex>
    WRITER$ = (org.apache.avro.io.DatumWriter<GroupByComplex>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GroupByComplex>
    READER$ = (org.apache.avro.io.DatumReader<GroupByComplex>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.key);

    out.writeLong(this.sum);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.key = in.readInt();

      this.sum = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.key = in.readInt();
          break;

        case 1:
          this.sum = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










