/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sortavro.avro_types.ranking;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MultipleRankWrappers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3192956887730308149L;
  public static final org.apache.avro.Schema SCHEMA$ = MultipleRankWrappersSchemaCreator.getSchema();
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<sortavro.avro_types.ranking.RankWrapper> records;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MultipleRankWrappers() {}

  /**
   * All-args constructor.
   * @param records The new value for records
   */
  public MultipleRankWrappers(java.util.List<sortavro.avro_types.ranking.RankWrapper> records) {
    this.records = records;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return records;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: records = (java.util.List<sortavro.avro_types.ranking.RankWrapper>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'records' field.
   * @return The value of the 'records' field.
   */
  public java.util.List<sortavro.avro_types.ranking.RankWrapper> getRecords() {
    return records;
  }

  /**
   * Sets the value of the 'records' field.
   * @param value the value to set.
   */
  public void setRecords(java.util.List<sortavro.avro_types.ranking.RankWrapper> value) {
    this.records = value;
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
