/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sortavro.record;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Record4Float extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4756935028409065295L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Record4Float\",\"namespace\":\"sortavro.record\",\"fields\":[{\"name\":\"first\",\"type\":\"float\"},{\"name\":\"second\",\"type\":\"float\"},{\"name\":\"third\",\"type\":\"float\"},{\"name\":\"fourth\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public float first;
  @Deprecated public float second;
  @Deprecated public float third;
  @Deprecated public float fourth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Record4Float() {}

  /**
   * All-args constructor.
   * @param first The new value for first
   * @param second The new value for second
   * @param third The new value for third
   * @param fourth The new value for fourth
   */
  public Record4Float(java.lang.Float first, java.lang.Float second, java.lang.Float third, java.lang.Float fourth) {
    this.first = first;
    this.second = second;
    this.third = third;
    this.fourth = fourth;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first;
    case 1: return second;
    case 2: return third;
    case 3: return fourth;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first = (java.lang.Float)value$; break;
    case 1: second = (java.lang.Float)value$; break;
    case 2: third = (java.lang.Float)value$; break;
    case 3: fourth = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first' field.
   * @return The value of the 'first' field.
   */
  public java.lang.Float getFirst() {
    return first;
  }

  /**
   * Sets the value of the 'first' field.
   * @param value the value to set.
   */
  public void setFirst(java.lang.Float value) {
    this.first = value;
  }

  /**
   * Gets the value of the 'second' field.
   * @return The value of the 'second' field.
   */
  public java.lang.Float getSecond() {
    return second;
  }

  /**
   * Sets the value of the 'second' field.
   * @param value the value to set.
   */
  public void setSecond(java.lang.Float value) {
    this.second = value;
  }

  /**
   * Gets the value of the 'third' field.
   * @return The value of the 'third' field.
   */
  public java.lang.Float getThird() {
    return third;
  }

  /**
   * Sets the value of the 'third' field.
   * @param value the value to set.
   */
  public void setThird(java.lang.Float value) {
    this.third = value;
  }

  /**
   * Gets the value of the 'fourth' field.
   * @return The value of the 'fourth' field.
   */
  public java.lang.Float getFourth() {
    return fourth;
  }

  /**
   * Sets the value of the 'fourth' field.
   * @param value the value to set.
   */
  public void setFourth(java.lang.Float value) {
    this.fourth = value;
  }

  /**
   * Creates a new Record4Float RecordBuilder.
   * @return A new Record4Float RecordBuilder
   */
  public static sortavro.record.Record4Float.Builder newBuilder() {
    return new sortavro.record.Record4Float.Builder();
  }

  /**
   * Creates a new Record4Float RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Record4Float RecordBuilder
   */
  public static sortavro.record.Record4Float.Builder newBuilder(sortavro.record.Record4Float.Builder other) {
    return new sortavro.record.Record4Float.Builder(other);
  }

  /**
   * Creates a new Record4Float RecordBuilder by copying an existing Record4Float instance.
   * @param other The existing instance to copy.
   * @return A new Record4Float RecordBuilder
   */
  public static sortavro.record.Record4Float.Builder newBuilder(sortavro.record.Record4Float other) {
    return new sortavro.record.Record4Float.Builder(other);
  }

  /**
   * RecordBuilder for Record4Float instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Record4Float>
    implements org.apache.avro.data.RecordBuilder<Record4Float> {

    private float first;
    private float second;
    private float third;
    private float fourth;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sortavro.record.Record4Float.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.second)) {
        this.second = data().deepCopy(fields()[1].schema(), other.second);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.third)) {
        this.third = data().deepCopy(fields()[2].schema(), other.third);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fourth)) {
        this.fourth = data().deepCopy(fields()[3].schema(), other.fourth);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Record4Float instance
     * @param other The existing instance to copy.
     */
    private Builder(sortavro.record.Record4Float other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.first)) {
        this.first = data().deepCopy(fields()[0].schema(), other.first);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.second)) {
        this.second = data().deepCopy(fields()[1].schema(), other.second);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.third)) {
        this.third = data().deepCopy(fields()[2].schema(), other.third);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fourth)) {
        this.fourth = data().deepCopy(fields()[3].schema(), other.fourth);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'first' field.
      * @return The value.
      */
    public java.lang.Float getFirst() {
      return first;
    }

    /**
      * Sets the value of the 'first' field.
      * @param value The value of 'first'.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder setFirst(float value) {
      validate(fields()[0], value);
      this.first = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first' field has been set.
      * @return True if the 'first' field has been set, false otherwise.
      */
    public boolean hasFirst() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first' field.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder clearFirst() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'second' field.
      * @return The value.
      */
    public java.lang.Float getSecond() {
      return second;
    }

    /**
      * Sets the value of the 'second' field.
      * @param value The value of 'second'.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder setSecond(float value) {
      validate(fields()[1], value);
      this.second = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'second' field has been set.
      * @return True if the 'second' field has been set, false otherwise.
      */
    public boolean hasSecond() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'second' field.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder clearSecond() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'third' field.
      * @return The value.
      */
    public java.lang.Float getThird() {
      return third;
    }

    /**
      * Sets the value of the 'third' field.
      * @param value The value of 'third'.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder setThird(float value) {
      validate(fields()[2], value);
      this.third = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'third' field has been set.
      * @return True if the 'third' field has been set, false otherwise.
      */
    public boolean hasThird() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'third' field.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder clearThird() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fourth' field.
      * @return The value.
      */
    public java.lang.Float getFourth() {
      return fourth;
    }

    /**
      * Sets the value of the 'fourth' field.
      * @param value The value of 'fourth'.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder setFourth(float value) {
      validate(fields()[3], value);
      this.fourth = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fourth' field has been set.
      * @return True if the 'fourth' field has been set, false otherwise.
      */
    public boolean hasFourth() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fourth' field.
      * @return This builder.
      */
    public sortavro.record.Record4Float.Builder clearFourth() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Record4Float build() {
      try {
        Record4Float record = new Record4Float();
        record.first = fieldSetFlags()[0] ? this.first : (java.lang.Float) defaultValue(fields()[0]);
        record.second = fieldSetFlags()[1] ? this.second : (java.lang.Float) defaultValue(fields()[1]);
        record.third = fieldSetFlags()[2] ? this.third : (java.lang.Float) defaultValue(fields()[2]);
        record.fourth = fieldSetFlags()[3] ? this.fourth : (java.lang.Float) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
