/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sequential_algorithms.types;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Complex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7626035616501863241L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Complex\",\"namespace\":\"sequential_algorithms.types\",\"fields\":[{\"name\":\"null_prim\",\"type\":[\"null\",\"int\"]},{\"name\":\"boolean_prim\",\"type\":\"boolean\"},{\"name\":\"int_prim\",\"type\":{\"type\":\"int\",\"arg.properties\":{\"range\":{\"min\":-100,\"max\":100}}}},{\"name\":\"long_prim\",\"type\":\"long\"},{\"name\":\"float_prim\",\"type\":\"float\"},{\"name\":\"double_prim\",\"type\":\"double\"},{\"name\":\"string_prim\",\"type\":\"string\"},{\"name\":\"bytes_prim\",\"type\":\"bytes\"},{\"name\":\"middle\",\"type\":{\"type\":\"record\",\"name\":\"MiddleNested\",\"fields\":[{\"name\":\"middle_array\",\"type\":{\"type\":\"array\",\"items\":\"float\"}},{\"name\":\"inner\",\"type\":{\"type\":\"record\",\"name\":\"InnerNested\",\"fields\":[{\"name\":\"inner_int\",\"type\":\"int\"},{\"name\":\"inner_string\",\"type\":\"string\"}]}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Complex> ENCODER =
      new BinaryMessageEncoder<Complex>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Complex> DECODER =
      new BinaryMessageDecoder<Complex>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Complex> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Complex> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Complex> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Complex>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Complex to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Complex from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Complex instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Complex fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer null_prim;
  @Deprecated public boolean boolean_prim;
  @Deprecated public int int_prim;
  @Deprecated public long long_prim;
  @Deprecated public float float_prim;
  @Deprecated public double double_prim;
  @Deprecated public java.lang.CharSequence string_prim;
  @Deprecated public java.nio.ByteBuffer bytes_prim;
  @Deprecated public sequential_algorithms.types.MiddleNested middle;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Complex() {}

  /**
   * All-args constructor.
   * @param null_prim The new value for null_prim
   * @param boolean_prim The new value for boolean_prim
   * @param int_prim The new value for int_prim
   * @param long_prim The new value for long_prim
   * @param float_prim The new value for float_prim
   * @param double_prim The new value for double_prim
   * @param string_prim The new value for string_prim
   * @param bytes_prim The new value for bytes_prim
   * @param middle The new value for middle
   */
  public Complex(java.lang.Integer null_prim, java.lang.Boolean boolean_prim, java.lang.Integer int_prim, java.lang.Long long_prim, java.lang.Float float_prim, java.lang.Double double_prim, java.lang.CharSequence string_prim, java.nio.ByteBuffer bytes_prim, sequential_algorithms.types.MiddleNested middle) {
    this.null_prim = null_prim;
    this.boolean_prim = boolean_prim;
    this.int_prim = int_prim;
    this.long_prim = long_prim;
    this.float_prim = float_prim;
    this.double_prim = double_prim;
    this.string_prim = string_prim;
    this.bytes_prim = bytes_prim;
    this.middle = middle;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return null_prim;
    case 1: return boolean_prim;
    case 2: return int_prim;
    case 3: return long_prim;
    case 4: return float_prim;
    case 5: return double_prim;
    case 6: return string_prim;
    case 7: return bytes_prim;
    case 8: return middle;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: null_prim = (java.lang.Integer)value$; break;
    case 1: boolean_prim = (java.lang.Boolean)value$; break;
    case 2: int_prim = (java.lang.Integer)value$; break;
    case 3: long_prim = (java.lang.Long)value$; break;
    case 4: float_prim = (java.lang.Float)value$; break;
    case 5: double_prim = (java.lang.Double)value$; break;
    case 6: string_prim = (java.lang.CharSequence)value$; break;
    case 7: bytes_prim = (java.nio.ByteBuffer)value$; break;
    case 8: middle = (sequential_algorithms.types.MiddleNested)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'null_prim' field.
   * @return The value of the 'null_prim' field.
   */
  public java.lang.Integer getNullPrim() {
    return null_prim;
  }


  /**
   * Sets the value of the 'null_prim' field.
   * @param value the value to set.
   */
  public void setNullPrim(java.lang.Integer value) {
    this.null_prim = value;
  }

  /**
   * Gets the value of the 'boolean_prim' field.
   * @return The value of the 'boolean_prim' field.
   */
  public boolean getBooleanPrim() {
    return boolean_prim;
  }


  /**
   * Sets the value of the 'boolean_prim' field.
   * @param value the value to set.
   */
  public void setBooleanPrim(boolean value) {
    this.boolean_prim = value;
  }

  /**
   * Gets the value of the 'int_prim' field.
   * @return The value of the 'int_prim' field.
   */
  public int getIntPrim() {
    return int_prim;
  }


  /**
   * Sets the value of the 'int_prim' field.
   * @param value the value to set.
   */
  public void setIntPrim(int value) {
    this.int_prim = value;
  }

  /**
   * Gets the value of the 'long_prim' field.
   * @return The value of the 'long_prim' field.
   */
  public long getLongPrim() {
    return long_prim;
  }


  /**
   * Sets the value of the 'long_prim' field.
   * @param value the value to set.
   */
  public void setLongPrim(long value) {
    this.long_prim = value;
  }

  /**
   * Gets the value of the 'float_prim' field.
   * @return The value of the 'float_prim' field.
   */
  public float getFloatPrim() {
    return float_prim;
  }


  /**
   * Sets the value of the 'float_prim' field.
   * @param value the value to set.
   */
  public void setFloatPrim(float value) {
    this.float_prim = value;
  }

  /**
   * Gets the value of the 'double_prim' field.
   * @return The value of the 'double_prim' field.
   */
  public double getDoublePrim() {
    return double_prim;
  }


  /**
   * Sets the value of the 'double_prim' field.
   * @param value the value to set.
   */
  public void setDoublePrim(double value) {
    this.double_prim = value;
  }

  /**
   * Gets the value of the 'string_prim' field.
   * @return The value of the 'string_prim' field.
   */
  public java.lang.CharSequence getStringPrim() {
    return string_prim;
  }


  /**
   * Sets the value of the 'string_prim' field.
   * @param value the value to set.
   */
  public void setStringPrim(java.lang.CharSequence value) {
    this.string_prim = value;
  }

  /**
   * Gets the value of the 'bytes_prim' field.
   * @return The value of the 'bytes_prim' field.
   */
  public java.nio.ByteBuffer getBytesPrim() {
    return bytes_prim;
  }


  /**
   * Sets the value of the 'bytes_prim' field.
   * @param value the value to set.
   */
  public void setBytesPrim(java.nio.ByteBuffer value) {
    this.bytes_prim = value;
  }

  /**
   * Gets the value of the 'middle' field.
   * @return The value of the 'middle' field.
   */
  public sequential_algorithms.types.MiddleNested getMiddle() {
    return middle;
  }


  /**
   * Sets the value of the 'middle' field.
   * @param value the value to set.
   */
  public void setMiddle(sequential_algorithms.types.MiddleNested value) {
    this.middle = value;
  }

  /**
   * Creates a new Complex RecordBuilder.
   * @return A new Complex RecordBuilder
   */
  public static sequential_algorithms.types.Complex.Builder newBuilder() {
    return new sequential_algorithms.types.Complex.Builder();
  }

  /**
   * Creates a new Complex RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Complex RecordBuilder
   */
  public static sequential_algorithms.types.Complex.Builder newBuilder(sequential_algorithms.types.Complex.Builder other) {
    if (other == null) {
      return new sequential_algorithms.types.Complex.Builder();
    } else {
      return new sequential_algorithms.types.Complex.Builder(other);
    }
  }

  /**
   * Creates a new Complex RecordBuilder by copying an existing Complex instance.
   * @param other The existing instance to copy.
   * @return A new Complex RecordBuilder
   */
  public static sequential_algorithms.types.Complex.Builder newBuilder(sequential_algorithms.types.Complex other) {
    if (other == null) {
      return new sequential_algorithms.types.Complex.Builder();
    } else {
      return new sequential_algorithms.types.Complex.Builder(other);
    }
  }

  /**
   * RecordBuilder for Complex instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Complex>
    implements org.apache.avro.data.RecordBuilder<Complex> {

    private java.lang.Integer null_prim;
    private boolean boolean_prim;
    private int int_prim;
    private long long_prim;
    private float float_prim;
    private double double_prim;
    private java.lang.CharSequence string_prim;
    private java.nio.ByteBuffer bytes_prim;
    private sequential_algorithms.types.MiddleNested middle;
    private sequential_algorithms.types.MiddleNested.Builder middleBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sequential_algorithms.types.Complex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.null_prim)) {
        this.null_prim = data().deepCopy(fields()[0].schema(), other.null_prim);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.boolean_prim)) {
        this.boolean_prim = data().deepCopy(fields()[1].schema(), other.boolean_prim);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.int_prim)) {
        this.int_prim = data().deepCopy(fields()[2].schema(), other.int_prim);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.long_prim)) {
        this.long_prim = data().deepCopy(fields()[3].schema(), other.long_prim);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.float_prim)) {
        this.float_prim = data().deepCopy(fields()[4].schema(), other.float_prim);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.double_prim)) {
        this.double_prim = data().deepCopy(fields()[5].schema(), other.double_prim);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.string_prim)) {
        this.string_prim = data().deepCopy(fields()[6].schema(), other.string_prim);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.bytes_prim)) {
        this.bytes_prim = data().deepCopy(fields()[7].schema(), other.bytes_prim);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.middle)) {
        this.middle = data().deepCopy(fields()[8].schema(), other.middle);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (other.hasMiddleBuilder()) {
        this.middleBuilder = sequential_algorithms.types.MiddleNested.newBuilder(other.getMiddleBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Complex instance
     * @param other The existing instance to copy.
     */
    private Builder(sequential_algorithms.types.Complex other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.null_prim)) {
        this.null_prim = data().deepCopy(fields()[0].schema(), other.null_prim);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.boolean_prim)) {
        this.boolean_prim = data().deepCopy(fields()[1].schema(), other.boolean_prim);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.int_prim)) {
        this.int_prim = data().deepCopy(fields()[2].schema(), other.int_prim);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.long_prim)) {
        this.long_prim = data().deepCopy(fields()[3].schema(), other.long_prim);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.float_prim)) {
        this.float_prim = data().deepCopy(fields()[4].schema(), other.float_prim);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.double_prim)) {
        this.double_prim = data().deepCopy(fields()[5].schema(), other.double_prim);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.string_prim)) {
        this.string_prim = data().deepCopy(fields()[6].schema(), other.string_prim);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bytes_prim)) {
        this.bytes_prim = data().deepCopy(fields()[7].schema(), other.bytes_prim);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.middle)) {
        this.middle = data().deepCopy(fields()[8].schema(), other.middle);
        fieldSetFlags()[8] = true;
      }
      this.middleBuilder = null;
    }

    /**
      * Gets the value of the 'null_prim' field.
      * @return The value.
      */
    public java.lang.Integer getNullPrim() {
      return null_prim;
    }


    /**
      * Sets the value of the 'null_prim' field.
      * @param value The value of 'null_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setNullPrim(java.lang.Integer value) {
      validate(fields()[0], value);
      this.null_prim = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'null_prim' field has been set.
      * @return True if the 'null_prim' field has been set, false otherwise.
      */
    public boolean hasNullPrim() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'null_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearNullPrim() {
      null_prim = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'boolean_prim' field.
      * @return The value.
      */
    public boolean getBooleanPrim() {
      return boolean_prim;
    }


    /**
      * Sets the value of the 'boolean_prim' field.
      * @param value The value of 'boolean_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setBooleanPrim(boolean value) {
      validate(fields()[1], value);
      this.boolean_prim = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'boolean_prim' field has been set.
      * @return True if the 'boolean_prim' field has been set, false otherwise.
      */
    public boolean hasBooleanPrim() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'boolean_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearBooleanPrim() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'int_prim' field.
      * @return The value.
      */
    public int getIntPrim() {
      return int_prim;
    }


    /**
      * Sets the value of the 'int_prim' field.
      * @param value The value of 'int_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setIntPrim(int value) {
      validate(fields()[2], value);
      this.int_prim = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'int_prim' field has been set.
      * @return True if the 'int_prim' field has been set, false otherwise.
      */
    public boolean hasIntPrim() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'int_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearIntPrim() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'long_prim' field.
      * @return The value.
      */
    public long getLongPrim() {
      return long_prim;
    }


    /**
      * Sets the value of the 'long_prim' field.
      * @param value The value of 'long_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setLongPrim(long value) {
      validate(fields()[3], value);
      this.long_prim = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'long_prim' field has been set.
      * @return True if the 'long_prim' field has been set, false otherwise.
      */
    public boolean hasLongPrim() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'long_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearLongPrim() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'float_prim' field.
      * @return The value.
      */
    public float getFloatPrim() {
      return float_prim;
    }


    /**
      * Sets the value of the 'float_prim' field.
      * @param value The value of 'float_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setFloatPrim(float value) {
      validate(fields()[4], value);
      this.float_prim = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'float_prim' field has been set.
      * @return True if the 'float_prim' field has been set, false otherwise.
      */
    public boolean hasFloatPrim() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'float_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearFloatPrim() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'double_prim' field.
      * @return The value.
      */
    public double getDoublePrim() {
      return double_prim;
    }


    /**
      * Sets the value of the 'double_prim' field.
      * @param value The value of 'double_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setDoublePrim(double value) {
      validate(fields()[5], value);
      this.double_prim = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'double_prim' field has been set.
      * @return True if the 'double_prim' field has been set, false otherwise.
      */
    public boolean hasDoublePrim() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'double_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearDoublePrim() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'string_prim' field.
      * @return The value.
      */
    public java.lang.CharSequence getStringPrim() {
      return string_prim;
    }


    /**
      * Sets the value of the 'string_prim' field.
      * @param value The value of 'string_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setStringPrim(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.string_prim = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'string_prim' field has been set.
      * @return True if the 'string_prim' field has been set, false otherwise.
      */
    public boolean hasStringPrim() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'string_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearStringPrim() {
      string_prim = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'bytes_prim' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBytesPrim() {
      return bytes_prim;
    }


    /**
      * Sets the value of the 'bytes_prim' field.
      * @param value The value of 'bytes_prim'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setBytesPrim(java.nio.ByteBuffer value) {
      validate(fields()[7], value);
      this.bytes_prim = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'bytes_prim' field has been set.
      * @return True if the 'bytes_prim' field has been set, false otherwise.
      */
    public boolean hasBytesPrim() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'bytes_prim' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearBytesPrim() {
      bytes_prim = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'middle' field.
      * @return The value.
      */
    public sequential_algorithms.types.MiddleNested getMiddle() {
      return middle;
    }


    /**
      * Sets the value of the 'middle' field.
      * @param value The value of 'middle'.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder setMiddle(sequential_algorithms.types.MiddleNested value) {
      validate(fields()[8], value);
      this.middleBuilder = null;
      this.middle = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'middle' field has been set.
      * @return True if the 'middle' field has been set, false otherwise.
      */
    public boolean hasMiddle() {
      return fieldSetFlags()[8];
    }

    /**
     * Gets the Builder instance for the 'middle' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public sequential_algorithms.types.MiddleNested.Builder getMiddleBuilder() {
      if (middleBuilder == null) {
        if (hasMiddle()) {
          setMiddleBuilder(sequential_algorithms.types.MiddleNested.newBuilder(middle));
        } else {
          setMiddleBuilder(sequential_algorithms.types.MiddleNested.newBuilder());
        }
      }
      return middleBuilder;
    }

    /**
     * Sets the Builder instance for the 'middle' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public sequential_algorithms.types.Complex.Builder setMiddleBuilder(sequential_algorithms.types.MiddleNested.Builder value) {
      clearMiddle();
      middleBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'middle' field has an active Builder instance
     * @return True if the 'middle' field has an active Builder instance
     */
    public boolean hasMiddleBuilder() {
      return middleBuilder != null;
    }

    /**
      * Clears the value of the 'middle' field.
      * @return This builder.
      */
    public sequential_algorithms.types.Complex.Builder clearMiddle() {
      middle = null;
      middleBuilder = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Complex build() {
      try {
        Complex record = new Complex();
        record.null_prim = fieldSetFlags()[0] ? this.null_prim : (java.lang.Integer) defaultValue(fields()[0]);
        record.boolean_prim = fieldSetFlags()[1] ? this.boolean_prim : (java.lang.Boolean) defaultValue(fields()[1]);
        record.int_prim = fieldSetFlags()[2] ? this.int_prim : (java.lang.Integer) defaultValue(fields()[2]);
        record.long_prim = fieldSetFlags()[3] ? this.long_prim : (java.lang.Long) defaultValue(fields()[3]);
        record.float_prim = fieldSetFlags()[4] ? this.float_prim : (java.lang.Float) defaultValue(fields()[4]);
        record.double_prim = fieldSetFlags()[5] ? this.double_prim : (java.lang.Double) defaultValue(fields()[5]);
        record.string_prim = fieldSetFlags()[6] ? this.string_prim : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.bytes_prim = fieldSetFlags()[7] ? this.bytes_prim : (java.nio.ByteBuffer) defaultValue(fields()[7]);
        if (middleBuilder != null) {
          try {
            record.middle = this.middleBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("middle"));
            throw e;
          }
        } else {
          record.middle = fieldSetFlags()[8] ? this.middle : (sequential_algorithms.types.MiddleNested) defaultValue(fields()[8]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Complex>
    WRITER$ = (org.apache.avro.io.DatumWriter<Complex>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Complex>
    READER$ = (org.apache.avro.io.DatumReader<Complex>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.null_prim == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.null_prim);
    }

    out.writeBoolean(this.boolean_prim);

    out.writeInt(this.int_prim);

    out.writeLong(this.long_prim);

    out.writeFloat(this.float_prim);

    out.writeDouble(this.double_prim);

    out.writeString(this.string_prim);

    out.writeBytes(this.bytes_prim);

    this.middle.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.null_prim = null;
      } else {
        this.null_prim = in.readInt();
      }

      this.boolean_prim = in.readBoolean();

      this.int_prim = in.readInt();

      this.long_prim = in.readLong();

      this.float_prim = in.readFloat();

      this.double_prim = in.readDouble();

      this.string_prim = in.readString(this.string_prim instanceof Utf8 ? (Utf8)this.string_prim : null);

      this.bytes_prim = in.readBytes(this.bytes_prim);

      if (this.middle == null) {
        this.middle = new sequential_algorithms.types.MiddleNested();
      }
      this.middle.customDecode(in);

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.null_prim = null;
          } else {
            this.null_prim = in.readInt();
          }
          break;

        case 1:
          this.boolean_prim = in.readBoolean();
          break;

        case 2:
          this.int_prim = in.readInt();
          break;

        case 3:
          this.long_prim = in.readLong();
          break;

        case 4:
          this.float_prim = in.readFloat();
          break;

        case 5:
          this.double_prim = in.readDouble();
          break;

        case 6:
          this.string_prim = in.readString(this.string_prim instanceof Utf8 ? (Utf8)this.string_prim : null);
          break;

        case 7:
          this.bytes_prim = in.readBytes(this.bytes_prim);
          break;

        case 8:
          if (this.middle == null) {
            this.middle = new sequential_algorithms.types.MiddleNested();
          }
          this.middle.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










